# TiFlash tiflash.toml Configuration File reference:
# https://docs.pingcap.com/tidb/stable/tiflash-configuration#configure-the-tiflashtoml-file

listen_host = "0.0.0.0"
path = "/data"

[flash]
service_addr = "0.0.0.0:3930"

[flash.proxy]
config = "/tiflash-learner.toml"

[logger]
errorlog = "/logs/tiflash_error.log"
log = "/logs/tiflash.log"

[raft]
pd_addr = "pd0:2379"

[storage.main]
dir = ["/data/flash"]
# capacity = [31457280]
