blank_issues_enabled: false
contact_links:
  - name: "\U0001F510 Security Vulnerabilities"
    url: "https://github.com/langgenius/dify/security/advisories/new"
    about: Report security vulnerabilities through GitHub Security Advisories to ensure responsible disclosure. ðŸ’¡ Please do not report security vulnerabilities in public issues.
  - name: "\U0001F4A1 Model Providers & Plugins"
    url: "https://github.com/langgenius/dify-official-plugins/issues/new/choose"
    about: Report issues with official plugins or model providers, you will need to provide the plugin version and other relevant details.
  - name: "\U0001F4AC Documentation Issues"
    url: "https://github.com/langgenius/dify-docs/issues/new"
    about: Report issues with the documentation, such as typos, outdated information, or missing content. Please provide the specific section and details of the issue.
  - name: "\U0001F4E7 Discussions"
    url: https://github.com/langgenius/dify/discussions/categories/general
    about: General discussions and seek help from the community
