version: '3'
services:
  # Chroma vector store.
  chroma:
    image: ghcr.io/chroma-core/chroma:0.5.1
    restart: always
    volumes:
      - ./volumes/chroma:/chroma/chroma
    environment:
      CHROMA_SERVER_AUTHN_CREDENTIALS: difyai123456
      CHROMA_SERVER_AUTHN_PROVIDER: chromadb.auth.token_authn.TokenAuthenticationServerProvider
      IS_PERSISTENT: TRUE
    ports:
      - "8000:8000"
