version: '3'
services:
  # Qdrant vector store.
  qdrant:
    image: langgenius/qdrant:v1.7.3
    restart: always
    volumes:
      - ./volumes/qdrant:/qdrant/storage
    environment:
      QDRANT_API_KEY: 'difyai123456'
    ports:
      - "6333:6333"
