apiVersion: v1
kind: Service
metadata:
  name: dify-worker
  namespace: acedatacloud
spec:
  type: ClusterIP
  selector:
    app: dify-worker
  ports:
    - name: http
      port: 5001
      targetPort: 5001
