apiVersion: v1
kind: Service
metadata:
  name: dify-sandbox
  namespace: acedatacloud
spec:
  type: ClusterIP
  selector:
    app: dify-sandbox
  ports:
    - name: http
      port: 8194
      targetPort: 8194
