apiVersion: v1
kind: Service
metadata:
  name: dify-api-headless
  namespace: acedatacloud
spec:
  clusterIP: None
  selector:
    app: dify-api
  ports:
    - name: http
      port: 5001
      targetPort: 5001

