apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: dify-api
    app.kubernetes.io/instance: dify-api
  name: dify-api
  namespace: acedatacloud
spec:
  minReadySeconds: 10
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dify-api
  serviceName: dify-api-headless
  template:
    metadata:
      labels:
        app: dify-api
    spec:
      automountServiceAccountToken: false
      initContainers:
      - name: init-permissions
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            FLAG_FILE="/app/api/storage/.init_permissions"
            if [ -f "$FLAG_FILE" ]; then
              echo "Permissions already initialized. Exiting."
              exit 0
            fi
            echo "Initializing permissions for /app/api/storage"
            chown -R 1001:1001 /app/api/storage && touch "$FLAG_FILE"
            echo "Permissions initialized. Exiting."
        volumeMounts:
        - mountPath: /app/api/storage
          name: dify-storage
          subPath: api-storage
      containers:
      - envFrom:
        - configMapRef:
            name: dify-env
        env:
        - name: MODE
          value: api
        - name: LOG_LEVEL
          value: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: SECRET_KEY
        - name: MIGRATION_ENABLED
          value: "true"
        - name: PLUGIN_DAEMON_URL
          value: http://dify-plugin-daemon:5002
        - name: PLUGIN_DAEMON_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: SECRET_KEY
        - name: INNER_API_KEY_FOR_PLUGIN
          valueFrom:
            secretKeyRef:
              name: dify
              key: SECRET_KEY
        - name: DB_TYPE
          value: postgresql
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: PGSQL_USER
              name: pgsql-qcloud
              optional: false
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: PGSQL_PASSWORD
              name: pgsql-qcloud
              optional: false
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: PGSQL_HOST
              name: pgsql-qcloud
              optional: false
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              key: PGSQL_PORT
              name: pgsql-qcloud
              optional: false
        - name: DB_DATABASE
          value: acedatacloud_dify
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: REDIS_HOST
              name: redis-qcloud
              optional: false
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              key: REDIS_PORT
              name: redis-qcloud
              optional: false
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: REDIS_PASSWORD
              name: redis-qcloud
              optional: false
        - name: REDIS_USE_SSL
          value: "false"
        - name: REDIS_DB
          value: "1"
        - name: REDIS_SERIALIZATION_PROTOCOL
          value: "2"
        - name: CELERY_BROKER_URL
          value: redis://:$(REDIS_PASSWORD)@$(REDIS_HOST):$(REDIS_PORT)/1
        - name: WEB_API_CORS_ALLOW_ORIGINS
          value: '*'
        - name: CONSOLE_CORS_ALLOW_ORIGINS
          value: '*'
        - name: STORAGE_TYPE
          value: opendal
        - name: OPENDAL_SCHEME
          value: fs
        - name: OPENDAL_FS_ROOT
          value: storage
        - name: VECTOR_STORE
          value: tencent
        - name: TENCENT_VECTOR_DB_URL
          valueFrom:
            secretKeyRef:
              key: DB_URL
              name: vdb-qcloud
              optional: false
        - name: TENCENT_VECTOR_DB_API_KEY
          valueFrom:
            secretKeyRef:
              key: DB_API_KEY
              name: vdb-qcloud
              optional: false
        - name: TENCENT_VECTOR_DB_TIMEOUT
          value: "30"
        - name: TENCENT_VECTOR_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: vdb-qcloud
              optional: false
        - name: TENCENT_VECTOR_DB_DATABASE
          value: acedatacloud_dify
        - name: TENCENT_VECTOR_DB_SHARD
          value: "1"
        - name: TENCENT_VECTOR_DB_REPLICAS
          value: "2"
        - name: TENCENT_VECTOR_DB_ENABLE_HYBRID_SEARCH
          value: "false"
        - name: CODE_EXECUTION_ENDPOINT
          value: http://dify-sandbox:8194
        - name: CODE_EXECUTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: dify
              key: SECRET_KEY
        - name: CODE_EXECUTION_SSL_VERIFY
          value: "True"
        - name: CODE_EXECUTION_POOL_MAX_CONNECTIONS
          value: "100"
        - name: CODE_EXECUTION_POOL_MAX_KEEPALIVE_CONNECTIONS
          value: "20"
        - name: CODE_EXECUTION_POOL_KEEPALIVE_EXPIRY
          value: "5.0"
        - name: CODE_EXECUTION_CONNECT_TIMEOUT
          value: "10"
        - name: CODE_EXECUTION_READ_TIMEOUT
          value: "60"
        - name: CODE_EXECUTION_WRITE_TIMEOUT
          value: "10"
        - name: CODE_MAX_NUMBER
          value: "9223372036854775807"
        - name: CODE_MIN_NUMBER
          value: "-9223372036854775808"
        - name: CODE_MAX_STRING_LENGTH
          value: "80000"
        - name: TEMPLATE_TRANSFORM_MAX_LENGTH
          value: "80000"
        - name: CODE_MAX_STRING_ARRAY_LENGTH
          value: "30"
        - name: CODE_MAX_OBJECT_ARRAY_LENGTH
          value: "30"
        - name: CODE_MAX_NUMBER_ARRAY_LENGTH
          value: "1000"
        - name: INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH
          value: "1000"
        image: ghcr.io/acedatacloud/dify-api:latest
        imagePullPolicy: IfNotPresent
        name: dify-api
        ports:
        - containerPort: 5001
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 10
        startupProbe:
          httpGet:
            path: /health
            port: 5001
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 20
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 512Mi
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /app/api/storage
          name: dify-storage
          subPath: api-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-registry
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dify-storage
        persistentVolumeClaim:
          claimName: dify
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
